### ISSUE TITLE
Show which video quality is active

### ISSUE THREAD

**Issue by FinixFighter** [OdyseeTeam/odysee-frontend#1041]
It would be nice to know which video quality is being used when the quality is set on "Auto".

Possible solution:
The most simple solution that bumps into my mind is adding a red dot next to the quality in use (for example, when you hover the cursor on the "auto" label, 720p would have a red dot next to it if 720p is in use).

**Comment by tzarebczan** [comment]
Thanks, like this idea!

**Comment by infinite-persistence** [comment]
If you can't find a solution to query the Auto's value, one idea is to re-use `plugins/videojs-http-streaming--override/playlist-selectors.js :: lastBandwidthSelector`.

- `const selectedBandwidth = simpleSelector()` tells you what Auto is selecting.
- The if-block below it can be removed, I just haven't removed since the override is disabled via `USE_ORIGINAL_STREAM_FOR_OPTIMIZED_AUTO`
