### ISSUE TITLE
incognito: double resolve on direct page load

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#1180]
If you refresh a content page, you get 2 resolves, 1 with is my input, and 1 without. Sometimes it doesn't happen. Shouldn't pass is_my_input if not authenticated (doesn't fail), and need to clean up the duplicate call.

**Comment by infinite-persistence** [comment]
One of the call comes from `doUserSetReferrer` called in `router`.  It wants to get the `permanent_url` as the referrer code, hence the `resolve`.
```
  useEffect(() => {
    if (!hasNavigated && hasUnclaimedRefereeReward && !isAuthenticated) {
      const valid = isURIValid(uri);
      if (valid) {
        const { path } = parseURI(uri);
        if (path !== 'undefined') setReferrer(path);
      }
    }
  }, [hasNavigated, uri, hasUnclaimedRefereeReward, setReferrer, isAuthenticated]);
```

Not sure how the referrer system works, but can it work without the permanent url?

If not, we probably need to move this effect from the router to somewhere else where the claim would be resolved anyway, like `page/Show`.  The problem is it needs to bring along `hasNavigated` and `hasUnclaimedRefereeReward` to wherever that destination is, which may or may not cause unwanted renders.

**Comment by tzarebczan** [comment]
It need the permanent url, probably not worth trying to go down this rabbit hole for now. The call is cached anyway...
