### ISSUE TITLE
Hyperlink recommended help page on Homepage customization

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#1215]
A user may go into homepage customization and then see recommended, but don't actually get any recommended content due to lack of view history or other items mentioned on the help page.

Would be nice to show the link when fyp fails to return

**Comment by infinite-persistence** [comment]
No issues with the suggestion, but brainstorming a bit ....
since the section itself already explains the situation, would the link-in-modal be redundant (they can re-open the modal to remove)?  
The other minor problem is that the dialog would also need to fetch the fyp in order to know if there are results (can do, just wanted to avoid clutter).

<img width="523" alt="image" src="https://user-images.githubusercontent.com/64950861/164024302-a8aafb71-8a1c-470d-ab19-5046cbe6431a.png">

**Comment by tzarebczan** [comment]
This is good enough, forgot we added it!
