### ISSUE TITLE
Changing quality should clear the cached video if the quality has been increased

### ISSUE THREAD

**Issue by Abwasserrohr** [OdyseeTeam/odysee-frontend#1270]
Maybe this should be rather in the video player repo or is a duplicate, sorry in that case. 😅

**Is your feature request related to a problem? Please describe.**
The player usually starts using the "Auto" mode and changing it will not clear the already played cached video out. I have seen people complain about why changing to 1080p doesn't improve the quality of the video and I think it's caused because it doesn't remove the cached video data and still uses the lower quality instead of the 1080p.

It's not like changing the quality is not working, but if I change it 10 seconds into the video and want to see the first 10 seconds in 1080p, I basicially can't, since it will force me to watch it in 144p/480p.

I have seen feedback from both creators and users that they think we're not worth it as a platform because of the low quality video we're delivering (yeah, these people overdramatize, but still), I know that it's not true, but people usually don't click around or try stuff and will just complain or leave.

**Describe the solution you'd like**
Clear the cached video out if the quality is changed to a higher resolution.

**Describe alternatives you've considered**
Auto Quality could start at 1080p and go down to lower resolutions if it has issues with loading instead of going up to higher resolutions. 

**Additional context**
POV: trying to watch the first 5 seconds of a video in 1080p:

https://user-images.githubusercontent.com/44294954/161297064-28ef00cf-3a95-466c-810b-c882ae964b68.mp4

**Comment by tzarebczan** [comment]
Don't think this is a big deal and don't think it's possible without resetting the entire video player from scratch, otherwise there's a trade off with having the video buffer / load (with spinner) when switched : https://github.com/videojs/http-streaming/pull/235/commits/9219955afa8c3858905c6aaef712faa925a346e1 . Don't think most people switch and then try to go back either, never done that personally.

We do have another issue to save and set quality setting to a user's preference, so that should help in most cases.

**Comment by tzarebczan** [comment]
Filed https://github.com/videojs/http-streaming/issues/1263 in case they want to add that also.
