### ISSUE TITLE
detect player errors and retry automatically, show retry button? 

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#1361]
There's some video js bug when switching resolutions, doesn't seem to common. When it happens, it just spins, can't switch anymore. Can this be detected and auto refreshed? 

![image](https://user-images.githubusercontent.com/8120721/164078219-06fc5a52-ee67-46f5-b7f0-183767d85d8c.png)

**Comment by Myzel394** [comment]
@tzarebczan How do you change the resolution? I can't find an option for that in the video player.

**Comment by tzarebczan** [comment]
Not all livestreams or files will have resolution options - try the featured page or livestreams from the various categories.

**Comment by tzarebczan** [comment]
This can also happen when the stream restarts due to various blips. Would be good to get fixed up soon!

**Comment by tzarebczan** [comment]
2 ways to cause this to happen on own stream, 1) start streaming, then stop for 15 seconds, and start again. 2) reset the stream via stream kill API (better, use the reset stream button)

**Comment by infinite-persistence** [comment]
Some early notes...

> _2 ways to cause this to happen on own stream, 1) start streaming, then stop for 15 seconds, and start again. 2) reset the stream via stream kill API (better, use the reset stream button)_

This seems to produce a different error, and it reconnects for me after 15-30s.

----

> _There's some video js bug when switching resolutions, doesn't seem to common. When it happens, it just spins, can't switch anymore._

By the way, is the following still relevant?  Saw some 404s and happened to stumbled upon it while looking:

```
https://github.com/gwuhaolin/livego/issues/206
```
----

> _Can this be detected and auto refreshed?_

:eyes:

**Comment by infinite-persistence** [comment]
## Idea 1
```
https://github.com/videojs/http-streaming/issues/1275
```

The person suggested to simply catch the errors, which implies we need to fork.  The idea of forking came up a few times, so maybe it's time, for small mergable changes like this.  Other issues where fork was suggested:
- The volume slider dragging problem -- a simple one-liner at the fork vs. a bunch of handling on our side.
- Move some of the single-instance changes there, instead of random places at React side.

## Idea 2
We won't get notification from `onError` since the vjs didn't capture.  The only pattern I see is a "`waiting` without an eventual `timeupdate`, stuck in `seeking`".  Keeping a timer and resetting when waited more than N seconds might work, but feels like a unreliable hack -- no idea if it covers 100% of the scenario.  

Looking for a more reliable marker -- the one in the screenshot below is showing `currentTime`, which continues to progress despite stuck (if it stayed the same, we could have used that).  `bufferedPercent` is always 0, never 1, (seems like a bug seen by others ), so can't use that either.

<img width="414" alt="image" src="https://user-images.githubusercontent.com/64950861/192262707-65b95b7f-28c1-496b-b738-12be8b88f279.png">

**Comment by tzarebczan** [comment]
How many times did you try the stream kill scenario? Definitely happens here, but a couple times it does recover. Maybe the stream needs to be transcoded also, and sometimes it varies if its running for 1 min vs 20 min (different media segment duration after 15 min).
