### ISSUE TITLE
Limit title length on frontend

### ISSUE THREAD

**Issue by Abwasserrohr** [OdyseeTeam/odysee-frontend#1544]
**Is your feature request related to a problem? Please describe.**
Sometimes, I see people uploading videos with very long titles and while it's not that important to change, it really doesn't look good if it happens and I'm also not sure if it may cause problems for SEO if we feed Google with such long titles.

**Describe the solution you'd like**
Limit titles to a length 100 (or 200) in the input field on creation and cut titles on frontend if longer.

**Alternatively**
Could also keep already existing 100+ entries and just create a input limit for new content.

**Additional context**
This [title](https://odysee.com/@quebecmedia:e/video_2022-05-11_19-04-30:1) has a length of over 2800:
![image](https://user-images.githubusercontent.com/44294954/169553123-36517900-8198-42fc-949c-f69504d415a9.png)

**Comment by Myzel394** [comment]
@Abwasserrohr I totally agree with you. A title should advertise a video, and a title with a length of 2800 chars is like having to watch a 2 hour ad on a YouTube video.

I'm not sure if it's possible to **force** a length of (let's say) under 100 chars, because of the blockchain - but like you already said, we can add a limit on the frontend (or at least show a warning). I can do a PR if that's okay.

**Comment by tzarebczan** [comment]
@toshokanneko is working on a publish page revamp so we can add it to that. I'd limit to the same that YouTube does, and maybe give a hint after X characters to consider shortening for best results.
