### ISSUE TITLE
adnim fall out

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#1583]
- [x] with premium on homepage load, briefly see in content ads 
  - <sub>Closed by #1589</sub>
- [ ] add incontent ads to category/channel pages (break up every X claims?), or add back bottom ad in those areas. 
  - <sub>Implemented the latter in #1599</sub>
- [ ] when ads are blocked, fill in in content units with premium promotion

**Comment by keikari** [comment]
* [ ] Sometimes large blurry ad on wild-west, or at the bottom of the page
Seen on Firefox, Chrome, Brave and at least on Firefox android

This seems to work to make it happen(same on video):
1. Go to home page
2. Go to some channel page
3. Scroll one page down (don't know if actually necessary, but makes easier to notice when ad has broken)
4. Repeat 1 - 3 until the ad breaks (It will be big at the end of the page before new claims load + also covering stuff in wild-west)

https://user-images.githubusercontent.com/34790748/170829293-308d00d0-949b-4f28-bb79-1fbbd35d591c.mp4

**Comment by infinite-persistence** [comment]
> _when ads are blocked, fill in in content units with premium promotion_

@toshokanneko, this one might need some design magic.  Maybe also need a new horizontal banner image?

**Comment by toshokanneko** [comment]
Hmmm...yeah, good point. A horizontal premium banner would definitely be better than repeating tiles xD Ideally something that could dynamically be cut on the sides...

**Comment by infinite-persistence** [comment]
- [ ] Even prior to adnim, the sticky doesn't load (reliably) when the homepage is loaded directly (F5, open) -- it loads fine when navigate into.

I thought it was due to our delay for Core Vitals, but seems like it is not the case since it is still happening after removing the delay.
(_note: we don't show the sticky in homepage right now -- was just making sure the code works for all pages_).
