### ISSUE TITLE
Stickers/emojis fall out / improvements

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#179]
- [x] Improve LBC sticker flow / clarity 
- [x] Show inline error if custom sticker amount is below min
- [x] improve quality of emojis

**Comment by infinite-persistence** [comment]
- [ ] Don't clear text-field if I sent a sticker first.
  - Just like in many chat apps, stickers and text comments are separate (expected behavior).  However, if I have text typed halfway, and then sent a sticker, the usual behavior is that the text is retained in the text-field so I can send it separately.  Currently, the text-field gets cleared.
