### ISSUE TITLE
local view position saving lost

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#20]
@tzarebczan commented on [Tue Jul 06 2021](https://github.com/lbryio/lbry-desktop/issues/6408)

We used to store and ensure view position started where you left off (locally), it broke recently. 

1) play a video for a few seconds
2) refresh the page
3) it should start where you were previously playing 

---

@tzarebczan commented on [Wed Jul 07 2021](https://github.com/lbryio/lbry-desktop/issues/6408#issuecomment-875756989)

This also breaks the "share at" feature and doesn't prefill the timestamp. 

---

@tzarebczan commented on [Fri Jul 16 2021](https://github.com/lbryio/lbry-desktop/issues/6408#issuecomment-881533858)

view position still broken (thought it was fixed at some point on Xander's branch, but I guess not) 

---

@tzarebczan commented on [Mon Jul 19 2021](https://github.com/lbryio/lbry-desktop/issues/6408#issuecomment-882642714)

Seems to be broke on transcoded videos, but works on non-transcoded 

---

@tzarebczan commented on [Thu Aug 19 2021](https://github.com/lbryio/lbry-desktop/issues/6408#issuecomment-901931170)

Looks like it's broken on both now (or just random where it works). Can't use the share at feature to prepopulate time, and if you do share a link with a time, it won't skip to it.

https://odysee.com/@FameFocus:b9/crazy-vfx-behind-prince-of-persia-vfx:3?r=5c3YqxEKm4urG5dwc81zNtkbXUP7BJGE&t=25

**Comment by infinite-persistence** [comment]
In most videos, `doFileGet | Lbry.get` is returning this as "file info":
```
{
  "streaming_url": "https://cdn.lbryplayer.xyz/api/v4/streams/free/the-final-fantasy-13-iceberg-explained/5e6ec4a7dc05c8c87691eb09bb51a6be89eed26a/c3e2cf"
}
```
![image](https://user-images.githubusercontent.com/64950861/139861861-3b2b4121-2a83-46e1-b603-f4e1f6e860c8.png)

Over at the UI, we determine the duration this way:
```
    const durationInSecs =
      fileInfo && fileInfo.metadata && fileInfo.metadata.video ? fileInfo.metadata.video.duration : 0;
```

Since `fileInfo` only contains `streaming_url`, the duration is 0 and was reset.  

SDK issue or code mistake? I see another `file_get` api in the code.

**Comment by tzarebczan** [comment]
Yea, that won't work on web - it should come from the claim resolve data. This may also be related: https://github.com/OdyseeTeam/odysee-frontend/issues/99 

What's strange it as it would work sometimes...

**Comment by david0178418** [comment]
Excuse the novel.  Just throwing in some notes from some poking around on this one.

It appears that there are multiple aspects to this bug that are interacting to make it appear somewhat random. @infinite-persistence, what you highlighted is one part.  This will nuke the video progress whenever you normally route to a video.

However, if you reload the page, it "works".  But that's actually due to another bug.  The `position` value in `onPlayerReady` in `videoViewer/view.jsx` is stale with the value that was initially loaded from storage.
![image](https://user-images.githubusercontent.com/128739/152091741-f5e88f9f-c8e6-4a88-bc2d-8b135153541f.png)

`position` is not in the `useCallback` dependency list, but that's not sufficient as it seems that the stale version of `onPlayerReady` is getting executed in the `useEffect` of `videojs.jsx`.

There's likely some general refactor here that can help here.

The next layer of the bug relates to multi tab/window.  When another tab is loaded, the other tabs do not get notified about updates to the store.  So `content.positions` gets overwritten with whatever values that window instance had, sometimes competing back and forth.

There are a few ways to approach this one.  The value of `content.store` could be pulled out of the indexeddb and merged with the new values on every save.  However, that would require reconstructing a copy of the store on every save, including all middlewares and transforms.  CPU expense aside, I haven't gone through the entire thing, so I'm not sure how much the store depends on being a singleton.

Another approach could be blacklisting this piece of state from redux-persist and store it separately.  That would make it easier to read/write.  Also, it's been a while since I've used indexeddb at a low level, but using localStorage would also have access to the 'storage' event, allowing all the tabs to stay in sync.  LocalForage could also have an extension that provides that functionality as well without concern for the storage target, but not sure here.

redux-persist also has a cross-tab notification npm module available, but I think that was dependent on the "storage" event.

**Comment by infinite-persistence** [comment]
Re: merging
Good find on the cross-tab problem.  I think the code originally only handled the Desktop (single tab) case.
If https://github.com/OdyseeTeam/odysee-frontend/issues/168 happens and becomes a syncable setting (`USER_STATE_POPULATE`), then maybe it will indirectly cover the cross-tab problem.

Re: dependancies
Yeah, looks like a bug.  The following line probably shouldn't be suppressed to remind us to update the dependency list (I just ported Xander's recsys code 1:1 without checking, oops).  Also, not sure if the dependancy list needs to be a variable -- if can't figure out why, can probably just put it back inline to avoid the other lint warning.
```
}, playerReadyDependencyList); // eslint-disable-line
```
