### ISSUE TITLE
%E2%80%8B or other characters appended on https urls crashes the app

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#202]
@jessopb commented on [Tue Jun 15 2021](https://github.com/lbryio/lbry-desktop/issues/6243)

Some pages have odysee links with 
`%E2%80%8B` appended.
https%3A%2F%2Fodysee.com%2F%40Franssen%3A3%E2%80%8B
This crashes the app.
I believe lbry-redux trying to use the i18n `__` function is failing.
1) strip %E2%80%8B
2) fix redux trying to use non-existent i18n function on errors

---

@marko-lorentz commented on [Mon Aug 16 2021](https://github.com/lbryio/lbry-desktop/issues/6243#issuecomment-899763371)

@sanabhass and me had a short look at the behaviour (not the code) and it seems as if the crash occurs for any URL that does not end with `:<hexnumber>`:
 
* https://odysee.com/@lusty:d/diablo-2-resurected-promesse-non-tenue:6 works fine
* https://odysee.com/@lusty:d/diablo-2-resurected-promesse-non-tenue:6x will break
* https://odysee.com/@lusty:d/diablo-2-resurected-promesse-non-tenue:6nice will break

The same happens when you break the format in the @-part of the URL which apparently needs `@<channel>:<hexnumber>`:
* https://odysee.com/@lusty:dk/diablo-2-resurected-promesse-non-tenue:6 will break

Conclusion based on Occam's razor: There is a custom parsing somewhere that assumes URLs to be exactly like `/@<channel>:<hexnumber>/<claim-title>:<hex number>`. 

Edit: 
After browsing through some code I would point to `lbry-redux/src/lbryURI.js` where function `parseURIModifier()` will throw an Error containing an i18n string when URI modifiers can not be parsed as expected. 

```
stack = "ReferenceError: __ is not defined
 at parseURIModifier (/Users/marko/Work/LBRY/git/lbry-desktop/web/node_modules/lbry-redux/dist/bundle.es.js:1600:5)
 at parseURI (/Users/marko/Work/LBRY/git/lbry-desktop/web/node_modules/lbry-redux/dist/bundle.es.js:1563:76)
 at getClaimFromChainqueryOrRedirect (/Users/marko/Work/LBRY/git/lbry-desktop/web/src/html.js:242:81)
 at getHtml (/Users/marko/Work/LBRY/git/lbry-desktop/web/src/html.js:325:25)
 at router.get (/Users/marko/Work/LBRY/git/lbry-desktop/web/src/routes.js:66:22)
 at dispatch (/Users/marko/Work/LBRY/git/lbry-desktop/web/node_modules/koa-compose/index.js:44:32)
 at next (/Users/marko/Work/LBRY/git/lbry-desktop/web/node_modules/koa-compose/index.js:45:18)
 at /Users/marko/Work/LBRY/git/lbry-desktop/web/node_modules/@koa/router/lib/router.js:346:16
[...]
```

**Comment by david0178418** [comment]
[Created a PR](https://github.com/OdyseeTeam/odysee-frontend/pull/715) that may be merged or possibly used as a template for any better solution someone more familiar with the environment might be able to use.

Here's the note I included on the ticket:

This PR may be used as more of a template for anyone more familiar with the codebase that may have a better solution.

The base issue is that the server code, which is run directly, does not know about the "__" global, which is included on the client side via the webpack "provide" plugin. As such, it has to be directly imported for use on the server. This, then, necessitates writing this subset of the dependency tree as common js, using "globalThis" instead of "window", and converting flow type annotations to comment annotations to be usable on both the node and client side.

**Comment by david0178418** [comment]
Added an update to the PR address the invisible character issue that is intertwined with this one.
