### ISSUE TITLE
Adding Item to Watch Later List Causes Frontend to Freeze

### ISSUE THREAD

**Issue by Loweville** [OdyseeTeam/odysee-frontend#3157]
**Bug**
When adding item to Watch Later list, the entire frontend freezes as it processes the action

**To Reproduce**

1. Go to any video preview element
2. Click on 'Watch Later'
3. Observe time to process task

**Expected behavior**
The site is still fully responsive and allows you to interact with anything like normal

**Screenshots**
N/A, not screen-shotable

**System Configuration**

Website (Odysee.com)

- LBRY Daemon version: N/A
- LBRY App version: N/A
- LBRY Installation ID: N/A
- Operating system: Linux

**Additional context**
I see that the Watch Later function utilizes react-redux's connect function, and the doPlaylistAddAndAllowPlaying function issues a dispatch request, I was wondering if there could be an opportunity to utilise Javascript Promises to allow it to run asynchronously, therefore it wouldn't freeze the frontend as the action was being performed.

**Comment by tzarebczan** [comment]
@keikari can you reproduce and take a look to see if there's any quick improvements possible?

**Comment by keikari** [comment]
I can see some freezing, from slight hiccup to seconds of freeze, depending of how many preview tiles have been loaded.  

I'm not 100% sure, but I think the `doPlaylistAddAndAllowPlaying` is already ran asynchronously and not the real culprit here.

And I think the actual issue is with redux store being updated multiple times while that is running, and when there are lot of preview tiles checking for new values from the store, it gets really heavy.  

Freezes get noticeably worse when scrolling down in some category. (Page 1 = ~60ms/render, Page 5 = 180ms/render)

Adding an item to Watch later 3 times on the page 1:
![2024-10-17_08-29](https://github.com/user-attachments/assets/42be8c5c-20c4-418e-bfab-4a0437019974)

Adding an item to Watch later 3 times on the page 5:
![2024-10-17_09-38](https://github.com/user-attachments/assets/f2525042-bc5b-4ab4-af16-7444f7996b33)

If I'm correct about the cause:  
ChatGPT says that `react-window` could be used so that only the items that are actually showing on the page get rendered. That sounds like something that can help to prevent worst cases of this.  
Will see if I can figure out the usage of that, and if it makes anything happen.

**Comment by keikari** [comment]
On initial testing using `react-window` does help with the performance, but not sure how to make it work properly.

**Comment by Loweville** [comment]
Hello, It's been a while. @tzarebczan, While I am a developer, I'm afraid I haven't got the time, nor am familiar enough with react to contribute to this issue.

I was also just wondering how this is progressing, I know these things tend to take time, no rush :laughing:

**Comment by infinite-persistence** [comment]
:wave: 

I think the tiles are not the main culprit, but it's the following chain:

- `doCollectionEdit`:
  - `doFetchItemsInCollection` (probably the bigger villain)
    - #3061 seems to now enforced this on every function call. Even if no network call was made (cached), the amount of loops and sorting is still huge. It takes 2s on a 10-item list for my slow PC.
  - `selectUrlsForCollectionId`
    - This loops through everything and calls `parseURI` which is very slow.
  - `selectCollectionForIdClaimForUriItem`
    - Loop again, `parseURI` again
  - ...+ maybe others
- (like Miko mentioned) actions hitting the store -> causes re-render, making it even worse if lots of tiles exist. But at least the profiling looks ok (mostly cached or "no renders")

## Suggestions
1. [Band-aid] Sprinkling the following at the right places will at least make the menu popup not freeze immediately. See `actions/comments` for similar examples.
    - <img src="https://github.com/user-attachments/assets/d8227096-9b2c-47ad-a92f-2546887058a9" width="150">
    - Pro: minimal code-changes
    - Cons: 
        - it will still eventually freeze if many videos are added in quick succession.  
        - many loops to find (although that 1 yield in the image seems sufficient for my side)
2. Or, don't use `doCollectionEdit` and create a leaner one, limiting it to WatchLater and Fav as a start.
    - Something like `ACTIONS.COLLECTION_ITEM_REMOVE | ADD` that:
        - Just need to verify the URL for that 1 item
        - Don't touch the rest of the items in the list
        - Insert/remove that entry. 
        - Update `updatedAt` to keep it the same way as `ACTIONS.COLLECTION_EDIT`
    - Pro:  Zero loops, lean
    - Con:  Not DRY (2 actions now)

**Comment by keikari** [comment]
Hello, and thanks!

If I recall right, I think I left it doing the `doFetchItemsInCollection` every edit as it didn't seemed slow, but pretty sure it didn't actually need to. So that one should be simple.

This should work just the same, and only does it once per list: https://github.com/OdyseeTeam/odysee-frontend/pull/3185
(But I don't think see that much of a difference in performance.)


I'm still blaming the tiles, since on first page I basically get no lag(maybe a very minor hiccup) when adding an item to a list of a 100 items. 
But if I scroll down the lag with adding item gets more noticeable. 

This is kind of a lag I'm seeing (from local instance)
<details>
<summary>Video</summary>

https://github.com/user-attachments/assets/e8c8db28-c906-4f03-b0d0-02590ba803e9
</details>

**Comment by infinite-persistence** [comment]
Any chance that the 2 dispatches with long names don't need that specific call sequence, i.e. can either be `batchActions`-ed  with `COLLECTION_EDIT`, or even just let `COLLECTION_EDIT` do it through an additional param[]?  

That's at least a band-aid to reduce the lag from increasing threefold for each extra tile (seeing ~4s down to ~0.5s, as an example)

**Comment by keikari** [comment]
Moved them in `COLLECTION_EDIT`(same PR). Does seem noticeably better now!

**Comment by Loweville** [comment]
@tzarebczan looks like the time the screen is frozen is consistent no matter how far down I scroll, good work there @infinite-persistence and @keikari

**Comment by tzarebczan** [comment]
Thanks for popping in @infinite-persistence !
