### ISSUE TITLE
Improve mobile view of comments when pinning is used

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#32]
@tzarebczan commented on [Thu Aug 26 2021](https://github.com/lbryio/lbry-desktop/issues/6971)

@infinite-persistence added a dismiss option for the pin right now to help

Otherwise the pin takes over most of the chat.

**Comment by infinite-persistence** [comment]
- [ ] I was planning to break apart `livestreamComments` (the entire right-bar section) so that we can stack sections on top of each other when in mobile view.  From recent livestream lag issue investigation, this now seems necessary for both desktop and web layout because whenever `livestreamComments` renders (e.g. on scroll), everything else renders too, and performance drops.

**Comment by tzarebczan** [comment]
this will be done as part of mobile chat improvements
