### ISSUE TITLE
Automatic language detection can't recognize `de-DE` as `de`

### ISSUE THREAD

**Issue by Abwasserrohr** [OdyseeTeam/odysee-frontend#656]
**Bug**
Usually, the site should automatically select the language of the browser, like Firefox does. Some browsers like Chrome do not send `de`, but `de-DE`. In fact, depending on the user, the German code could be:
`de-AT` German (Austria)
`de-CH` German (Switzerland)
`de-DE` German (Germany)
`de-LI` German (Liechtenstein)
`de-LU` German (Luxembourg)

**To Reproduce**
1. Set your system to German
2. Check in the console if `navigator.languages` returns `['de-DE']` and not `['de']`
2. Visit odysee.com on a new Chrome profile, it will not change the language or content on odysee.com

**Expected behavior**
If it can't find the language, split the language string at `-` and just use the first part, in this case `de`, the latter part isn't important. I'm seeing more complaints recently about almost no German content and think it's also due to the automatic language detection not working in many cases, this seems to affect quite a lot of people.

Console in Chrome (German):
![de-de](https://user-images.githubusercontent.com/44294954/148692785-e50daf58-a9ad-490c-80c2-a1b63695d871.png)
Request Header looks like this for me on Chrome: `accept-language: de-DE,de;q=0.9`

**Comment by zark0-UwU** [comment]
I have noticed in firefox, I do not get the web page on the configured language [Spanish (spain)]
the output to `navigator.languages` is `Array(4) [ "es-ES", "es", "en-US", "en" ]`

Also on my first request to https://odysee.com/ I have this on the request header: 
`Accept-Language: es-ES,es;q=0.8,en-US;q=0.5,en;q=0.3`

Is it because there is no Spanish translation, or because the odysee frontend does not understand what firefox is sending?
I am both a native Spanish speaker and a developer so either way I might be able to help.

Not very comfortable using electron tho, so if i give a solution it would be using pure js, so maybe not the best solution

**Comment by infinite-persistence** [comment]
> _If it can't find the language, split the language string at - and just use the first part_

I got this code got lost during a revert or merge.  Let me take stab at it ...

**Comment by zark0-UwU** [comment]
Wow! super fast @infinite-persistence I think your solution may help with chrome, but in firefox, i believe this is an array, but i'll have to look at that
Hopefully I'll check that today.

**Comment by zark0-UwU** [comment]
> I think the array version is `navigator.languages`, which seems like still in beta form. `navigator.language` will be in string form

Yep, that is exactly how it works, just checked on the oficial web page, since it is already merged, and it works flawlessly
